FROM oven/bun:1.3-alpine AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build-only

FROM oven/bun:1.3-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist

RUN bun install -g serve

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]